sudo: true
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - pip install codecov
  - pip install pipenv

# command to install dependencies
install:   
  - pipenv install --dev --system

# command to run tests
script: 
  - pytest --cov

after_success:
  - codecov
